name: Build and Deploy MixMods Browser

on:
  workflow_dispatch:

jobs:
  debug-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show the directory we are in
        run: pwd

      - name: List all files recursively
        run: ls -R
