name: Scrape MixMods Data

on:
  schedule:
    # Runs at 06:00 UTC every day
    - cron: '0 6 * * *'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use a Long-Term Support version

      - name: Install dependencies
        run: npm install

      - name: Run scraper script
        run: node scraper.js

      - name: Commit and push if data changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Automated: Update mod data'
          file_pattern: 'data.json'
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'actions@github.com'
          commit_author: 'GitHub Actions Bot <actions@github.com>'
