name: Scrape MixMods Data

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

# Add this permissions block. It's crucial.
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: scraper/package.json

      - name: Install dependencies
        run: npm install
        working-directory: ./scraper

      - name: Run scraper
        run: node scrape.js
        working-directory: ./scraper

      - name: Commit and push if data changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Automated: Update mod data'
          file_pattern: 'data.json'
